import Link from 'next/link'
import { ArrowDown, ArrowUpRight, Plus } from 'lucide-react'
import { CTA, SectionHeading } from '@/components/site-shell'
import { IndustryGrid, ProjectGrid, ServiceList } from '@/components/interactive-sections'
import { clients, process } from '@/lib/site-data'

export default function Page() { return <main>
  <section className="hero"><div className="hero-image" /><div className="blueprint-grid" /><div className="container hero-content"><p className="eyebrow eyebrow-red">Branding · Retail · Experience · Execution</p><h1>Building brands<br />beyond the <em>ordinary.</em></h1><p className="hero-copy">From brand environments and retail experiences to architectural execution and high-impact advertising, we turn ideas into experiences people remember.</p><div className="hero-actions"><Link href="/contact" className="button button-red">Start a project <ArrowUpRight size={18} /></Link><Link href="/portfolio" className="text-link light-link">Explore our work <ArrowDown size={17} /></Link></div></div><div className="hero-index">01 <span>/</span> 04</div></section>
  <section className="client-strip"><div className="container trust-inner"><div className="trust-heading"><p className="eyebrow">Trusted to bring brands to life</p><h2>Big names.<br /><em>Real presence.</em></h2><span className="trust-rule" /></div><div className="client-showcase"><p className="trust-note">Selected brand relationships</p><div className="client-row">{clients.map((client, index) => <span className={`client-chip chip-${index % 4}`} key={client}><i />{client}</span>)}</div><div className="trust-bottom"><span>Brand confidence, built into every touchpoint.</span><Link href="/portfolio" className="text-link">See the work <ArrowUpRight size={17} /></Link></div></div></div></section>
  <section className="section intro-section"><div className="container intro-grid"><div className="intro-art"><div className="art-line" /><div className="art-circle" /><span>AD<br />AW</span></div><div><p className="eyebrow">The real-world advantage</p><h2>We don’t just advertise brands.<br /><em>We build their presence.</em></h2><p className="lead">AD ADWISER combines strategic thinking, creative design and real-world execution to create memorable brand environments and experiences.</p><p>Across branding, retail environments, architectural branding, advertising, 3D visualization, events, OOH and physical brand execution, we are the partner that carries an idea from first sketch to final installation.</p><Link href="/about" className="text-link">More about AD ADWISER <ArrowUpRight size={17} /></Link></div></div></section>
  <section className="section capabilities-section"><div className="container"><SectionHeading eyebrow="Our capabilities" title="What we do" description="The thinking, making and doing behind brands that live in the real world." /><ServiceList /></div></section>
  <section className="section work-section"><div className="container"><div className="section-heading-row"><SectionHeading eyebrow="Selected work" title="Work that speaks for the brand." /><Link href="/portfolio" className="text-link">View all projects <ArrowUpRight size={17} /></Link></div><ProjectGrid limit={5} /></div></section>
  <section className="dark-section principles-section"><div className="container"><SectionHeading light eyebrow="Our point of view" title="From idea to impact." /><div className="principles-grid">{[['01','Strategy','We begin with understanding the brand, audience and objective.'],['02','Creativity','We transform strategic thinking into distinctive visual experiences.'],['03','Execution','We turn concepts into physical, visible brand experiences.'],['04','Consistency','We maintain brand quality across every touchpoint.']].map(([number,title,text]) => <div className="principle" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
  <section className="section process-section"><div className="container"><SectionHeading eyebrow="Our method" title="How we bring ideas to life" /><div className="process-grid">{process.map(([number,title,text]) => <div className="process-step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div>{number !== '06' && <Plus className="process-plus" size={17} />}</div>)}</div></div></section>
  <section className="section industry-section"><div className="container"><SectionHeading eyebrow="Where we work" title="Built for different industries. Designed for impact." /><IndustryGrid limit={6} /></div></section>
  <section className="statement-section"><div className="container statement-grid"><div><p className="eyebrow eyebrow-red">What scale looks like</p><h2>One partner.<br /><em>Every touchpoint.</em></h2></div><div className="statements"><div><strong>END-TO-END</strong><span>Creative to execution</span></div><div><strong>MULTI-SECTOR</strong><span>Brand experiences across industries</span></div><div><strong>CONCEPT TO COMPLETION</strong><span>One partner from idea to installation</span></div><div><strong>NATIONWIDE</strong><span>Local expertise with broad capability</span></div></div></div></section>
  <section className="section testimonial-section"><div className="container testimonial"><div className="quote-mark">“</div><blockquote>AD ADWISER helped us turn a complex brand vision into a physical experience that feels clear, confident and unmistakably ours.</blockquote><p>Placeholder testimonial · Replace with client approval</p></div></section>
  <CTA />
</main> }
